# Generated by Django 5.1.4 on 2024-12-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_or_domain', models.CharField(max_length=255, verbose_name='айпи/домен')),
                ('status', models.CharField(choices=[('vulnerable', 'Vulnerable'), ('not_vulnerable', 'Not Vulnerable'), ('error', 'Error')], max_length=50)),
                ('applied_exploits', models.TextField(verbose_name='прикладные эксплойты')),
                ('services_found', models.TextField(blank=True, null=True, verbose_name='найденные сервисы')),
                ('scan_date', models.DateTimeField(auto_now_add=True, verbose_name='дата сканирования')),
            ],
            options={
                'verbose_name': 'рузльтат сканирования',
                'verbose_name_plural': 'результаты сканирования',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vul_id', models.CharField(max_length=100, unique=True, verbose_name='айди уязвимости')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('published_date', models.DateTimeField(verbose_name='дата публикации')),
                ('source_url', models.URLField(verbose_name='исходная ссылка')),
                ('exploit_data', models.TextField(blank=True, null=True, verbose_name='эксплойты и PoC')),
            ],
            options={
                'verbose_name': 'уязвимость',
                'verbose_name_plural': 'уязвимости',
                'ordering': ('-id',),
            },
        ),
    ]
