# Generated by Django 5.1.4 on 2024-12-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exploit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('source_url', models.URLField()),
                ('exploit_links', models.TextField()),
            ],
        ),
    ]
